### ISSUE TITLE
Animals dead and elevator gone

### ISSUE THREAD

**Issue by Sjorvii** [toquidapus/Necohydra#1]
My animals have disappeared. All of them. The fish, the axolotls, the frogs, my sheep, my cow, my chickens, and my horse. My elevator (A contraption, counted as an entity) is also gone. I am currently trying to remedy this, by finding new animals and rebuilding the elevator, but animals are hard to find with these mods.

**Comment by toquidapus** [comment]
This was a only an issue on the server, due to command blocks made by another admin.
